- type: job
  id: TribalElder
  name: job-name-tribal-elder
  playTimeTracker: TribalElder
  startingGear: TribalElderGear
  icon: "Botanist"
  supervisors: job-supervisors-tribal-elder
  access:
  - Tribal

- type: startingGear
  id: TribalElderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
