- type: job
  id: Tribal
  name: job-name-tribal
  playTimeTracker: Tribal
  startingGear: TribalGear
  icon: "Botanist"
  supervisors: job-supervisors-tribal
  access:
  - Tribal

- type: startingGear
  id: TribalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
