- type: job
  id: TribalHealer
  name: job-name-tribal-healer
  playTimeTracker: TribalHealer
  startingGear: TribalHealerGear
  icon: "Botanist"
  supervisors: job-supervisors-tribal
  access:
  - Tribal

- type: startingGear
  id: TribalHealerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
