- type: job
  id: WastelandMusician
  name: job-name-musician
  playTimeTracker: WastelandMusician
  startingGear: WastelandMusicianGear
  icon: "Musician"
  supervisors: job-supervisors-hire
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: WastelandMusicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerPurple
    back: ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
    id: MusicianPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelMusicianFilled
  duffelbag: ClothingBackpackDuffelMusicianFilled
