- type: job
  id: WastelandReporter
  name: job-name-reporter
  playTimeTracker: WastelandReporter
  startingGear: WastelandReporterGear
  icon: "Reporter"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelandReporterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
